### ISSUE TITLE
Polling loops in new conversation after previous one was closed by agent

### ISSUE THREAD

**Issue by alecam** [microsoft/omnichannel-chat-sdk#90] opened 2021-11-08 14:28 UTC
Hello @xTEddie,
I ran into a critical bug: If the current conversation is closed by an agent, I call endChat().
If then I start a new chat, sometimes the poll request loops infinitely and the chat is no longer usable.

![image](https://user-images.githubusercontent.com/17322025/140759712-5ac5819a-ed3b-43d5-9674-02a44b57f0a5.png)

**Comment by xTEddie** [comment] 2021-11-16 22:13
- Does this happen on the latest version of ChatSDK?
- What is the `widgetId`?

**Comment by alecam** [comment] 2021-11-17 15:30
> * Does this happen on the latest version of ChatSDK?
> * What is the `widgetId`?

It happens on the latest versione of ChatSDK (1.0.0).
widgetId is 96f7b9a9-92d8-48b8-9a6e-f03d04c3c226

**Comment by marcorm** [comment] 2021-11-23 10:05
Hi @xTEddie any updates on this issue?

**Comment by xTEddie** [comment] 2021-12-15 00:41
I am unable to reproduce this issue on my end. I will be closing this issue for the moment. 

But please do reopen if you're able to reproduce the issue again and provide its `widgetId`, `timestamp`, `requestId` and `chatId` for further investigations.

**Closed by xTEddie** 2021-12-15 00:41 UTC

**Comment by alecam** [comment] 2021-12-16 10:54
Hi @xTEddie, here is a GitHub repository with a basic implementation that can reproduce the issue.
[https://github.com/alecam/omnichannel-sdk-looping-issue-demo](https://github.com/alecam/omnichannel-sdk-looping-issue-demo)

Steps to reproduce:

1. Click on **Start new chat** button and wait for the conversation to start;
2. Catch the conversation from the agent side;
3. End the conversation from the agent side;
4. Click on **Start new chat** button to start a new conversation;
5. After some time (with conversation Open) you should see the loop in the polling calls.

If you need to change orgId, orgUrl and widgetId, they are located at rows 11,12 and 13 of the src/App.js file.

Thank you.
