### ISSUE TITLE
ACSClientJoinConversationFailed Error

### ISSUE THREAD

**Issue by jelly1029** [microsoft/omnichannel-chat-sdk#134] opened 2022-05-13 03:43 UTC
![image](https://user-images.githubusercontent.com/12263729/168206979-85d3507c-0287-415b-a169-556f255d319e.png)
hi, we can trigger send chat request to omnichannel, but it return error and other event api is not working now. Do you know what will cause this issue?

**Comment by xTEddie** [comment] 2022-05-13 23:08
1. Did you try to uptake to the latest version of ChatSDK?
2. Can you please try your chat widget on the following sample app?
You can connect to your chat widget via the query params: `https://vvfog.csb.app/?orgId=[orgId]&orgUrl=[orgUrl]&widgetId=[widgetId]`

    source code: https://codesandbox.io/s/omnichannel-chat-sdk-botframework-webchat-control-vvfog

I am currently not able to reproduce this issue.

**Comment by jelly1029** [comment] 2022-05-17 06:43
hi, we try to troubleshoot the issue, because we are not using react app to develop this sdk.
our finding is the LiveChatVersion is upgraded already, we cant get the chatservice, is it possible to using v1 or previous version service?

**Comment by xTEddie** [comment] 2022-05-17 19:17
1. How are you developing your app?
2. As of May 2022, we started migrating organizations to the new messaging platform. We did sent a communication in October 2021. More info can be found [here](https://docs.microsoft.com/en-us/dynamics365/customer-service/migrate-acs)

**Comment by jelly1029** [comment] 2022-05-18 00:27
currently we using https://browserify.org/ to compile typescript sdk to js, we bypass telemetry react-native part, so will cause the issue?

**Comment by jelly1029** [comment] 2022-05-18 01:17
is it possible to maintain current old platform until we develop react version for this?

**Comment by xTEddie** [comment] 2022-05-18 05:46
Can you please provide the `orgId`? I will reach out to the team and get back to you regarding this.

**Comment by jelly1029** [comment] 2022-05-18 06:00
orgID : 0cd859b2-1c0b-43a4-8a22-bc987faac15a
orgUrl: https://orgdfbd3adc-crm5.omnichannelengagementhub.com
widgetId: da984994-40aa-47d2-a748-3327f3fbbae4

**Comment by xTEddie** [comment] 2022-05-18 20:43
Our team temporarily disabled `v2` in your org. Please keep in mind that `v1` will be decommissioned very soon. I'd recommend to perform the changes by June 10th at the latest. I'd also recommend to test the changes on `v2` to ensure backward compatibility

**Comment by jelly1029** [comment] 2022-05-19 10:04
hi teddie we using another way to achieve react sdk version, thanks for your help.
now we testing with new version.

**Comment by xTEddie** [comment] 2022-05-19 10:21
Can you please elaborate?

**Comment by jelly1029** [comment] 2022-05-20 08:25
Hi, currently we are using react version to test our service website, can i know can i test with v2 with sdk 1.1.0 because currently v2 is disable by your team? If we create new widget, is it v2? or need another org omnichannel just can work with v2.

**Comment by xTEddie** [comment] 2022-05-23 18:55
If you created a new widget in the same org, it will still be v1 since our team disabled v2 in that specific org. If you had another org, where the solution was recently upgraded, the chat messaging platform v2 should be enabled. You can validate by looking at the chat config `LiveChatVersion`. 

I'd suggest to have a dev/preproduction org where you can validate all the necessary changes on v2 before we switched back to v2 on that specific org.

**Comment by jelly1029** [comment] 2022-05-24 02:47
ok thanks

**Comment by jelly1029** [comment] 2022-05-27 09:27
Hi teddie, we found that the [OutOfOperatingHours] properties is always false after i setting or not.
Can you check for it? i tested v1 and v2 environment also same issue.
![image](https://user-images.githubusercontent.com/12263729/170671841-89bd2eb0-1915-4caa-8672-6c46c89bcaa4.png)


> If you created a new widget in the same org, it will still be v1 since our team disabled v2 in that specific org. If you had another org, where the solution was recently upgraded, the chat messaging platform v2 should be enabled. You can validate by looking at the chat config `LiveChatVersion`.
> 
> I'd suggest to have a dev/preproduction org where you can validate all the necessary changes on v2 before we switched back to v2 on that specific org.

**Comment by xTEddie** [comment] 2022-05-31 19:09
Does this issue still occur? Do you have the chat widget with the operating hours set up?

**Comment by jelly1029** [comment] 2022-06-01 00:33
yes whether i turn on/off the operating hours, the property still same

**Comment by xTEddie** [comment] 2022-06-07 21:22
How is the migration going so far? Any blockers?

**Comment by jelly1029** [comment] 2022-06-08 01:25
still ok, we are testing at different platform, thanks.

**Comment by jelly1029** [comment] 2022-06-10 01:54
yes you can , thanks !

**Comment by jelly1029** [comment] 2022-06-13 00:32
can i know when will switch to v2?

**Comment by xTEddie** [comment] 2022-06-13 18:05
I will pass the message to the team. I will let you know when the org has been switched.

**Comment by xTEddie** [comment] 2022-06-13 19:30
We're targeting June 15th 8AM PST on the migration.

**Comment by xTEddie** [comment] 2022-06-15 22:05
Migration is complete. Please let me know if we can close this issue.

**Comment by jelly1029** [comment] 2022-06-17 00:37
Yes, you may close this. Thanks!

**Closed** 2022-06-17 06:22 UTC
